In [1]:
import pandas as pd
print(pd.__version__)
#Подключение библиотеки для работы с таблицами

3.0.3

In [2]:
df= pd.read_csv(r'C:\Users\nikry\fintech_analysis\students.csv', delimiter = ',') 
#чтение csv файла и загрузка в пременную

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [ ]:
df['Growth'].mean()
#метод вычисления среднего значения

np.float64(170.66129032258064)

In [18]:
df['Weight'].mean()
#метод вычисления среднего значения

np.float64(64.03184713375796)

In [ ]:
df['Growth'].describe()
#проверка совпадения среднего значения

count    186.000000
mean     170.661290
std        9.055881
min      153.000000
25%      164.000000
50%      169.000000
75%      178.000000
max      197.000000
Name: Growth, dtype: float64

In [ ]:
df['Growth'].median()
#вывод медианы (50%)

np.float64(169.0)

In [19]:
df['Weight'].median()
#вывод медианы (50%)

np.float64(60.0)

In [ ]:
df['Growth'].min()
#вывод минимального значения

np.int64(153)

In [ ]:
df['Weight'].min()
#вывод минимального значения

np.float64(3.0)

In [ ]:
df['Weight'].max()
#вывод максимального значения

np.float64(120.0)

In [23]:
df['Rock paper scissors'].value_counts()

Rock paper scissors
Ножницы    88
Камень     60
Бумага     38
Name: count, dtype: int64

In [11]:
df['Growth'].min(), df['Growth'].max(), df['Growth'].std()

(np.int64(153), np.int64(197), np.float64(9.055880959226972))

In [13]:
df_cut = df[['Growth', 'Weight', 'Sex', 'Age']]
#оставляем только нужные столбцы

In [14]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Growth  186 non-null    int64
 1   Weight  157 non-null    float64
 2   Sex     186 non-null    str
 3   Age     186 non-null    int64
dtypes: float64(1), int64(2), str(1)
memory usage: 5.9 KB

In [15]:
df_cut.head()

   Growth  Weight      Sex  Age
0     170    64.0  женский   20
1     191    73.0  мужской   22
2     172    60.0  мужской   21
3     168    59.0  женский   19
4     159    57.0  женский   23

In [25]:
df_cut2 = df[['Weight', 'Sex']]

In [ ]:
df_cut2.head(10)

   Weight      Sex
0    64.0  женский
1    73.0  мужской
2    60.0  мужской
3    59.0  женский
4    57.0  женский
5    50.0  мужской
6    55.0  мужской
7   120.0  мужской
8    69.0  мужской
9    58.0  женский