In [1]:
import pandas as pd
print(pd.__version__)
#Подключение библиотеки для работы с таблицами

3.0.3

In [2]:
df= pd.read_csv(r'C:\Users\nikry\fintech_analysis\students.csv', delimiter = ',') 
#чтение csv файла и загрузка в пременную

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    str
 23  Sex                          186 non-null    str
 24  Problems in last semester    186 non-null    str
 25  Coin                         186 non-null    str
 26  Rock paper scissors          186 non-null    str
 27  Animal                       186 non-null    str
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    str
 30  Fastfood                     186 non-null    str
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    str
 35  Hostel                       186 non-null    str
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    str
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    str
 42  Your insitute                186 non-null    str
 43  Brother-sister               186 non-null    str
 44  Plane seat                   186 non-null    str
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), str(15)
memory usage: 69.9 KB

In [4]:
df['Growth'].mean()
#метод вычисления среднего значения

np.float64(170.66129032258064)

In [5]:
df['Weight'].mean()
#метод вычисления среднего значения

np.float64(64.03184713375796)

In [6]:
df['Growth'].describe()
#проверка совпадения среднего значения

count    186.000000
mean     170.661290
std        9.055881
min      153.000000
25%      164.000000
50%      169.000000
75%      178.000000
max      197.000000
Name: Growth, dtype: float64

In [7]:
df['Growth'].median()
#вывод медианы (50%)

np.float64(169.0)

In [8]:
df['Weight'].median()
#вывод медианы (50%)

np.float64(60.0)

In [9]:
df['Growth'].min()
#вывод минимального значения

np.int64(153)

In [10]:
df['Weight'].min()
#вывод минимального значения

np.float64(3.0)

In [11]:
df['Weight'].max()
#вывод максимального значения

np.float64(120.0)

In [12]:
df['Rock paper scissors'].value_counts()

Rock paper scissors
Ножницы    88
Камень     60
Бумага     38
Name: count, dtype: int64

In [13]:
df['Growth'].min(), df['Growth'].max(), df['Growth'].std()

(np.int64(153), np.int64(197), np.float64(9.055880959226972))

In [14]:
df_cut = df[['Growth', 'Weight', 'Sex', 'Age']]
#оставляем только нужные столбцы

In [15]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Growth  186 non-null    int64
 1   Weight  157 non-null    float64
 2   Sex     186 non-null    str
 3   Age     186 non-null    int64
dtypes: float64(1), int64(2), str(1)
memory usage: 5.9 KB

In [16]:
df_cut.head()

   Growth  Weight      Sex  Age
0     170    64.0  женский   20
1     191    73.0  мужской   22
2     172    60.0  мужской   21
3     168    59.0  женский   19
4     159    57.0  женский   23

In [17]:
df_cut2 = df[['Weight', 'Sex']]

In [18]:
df_cut2.head(10)

   Weight      Sex
0    64.0  женский
1    73.0  мужской
2    60.0  мужской
3    59.0  женский
4    57.0  женский
5    50.0  мужской
6    55.0  мужской
7   120.0  мужской
8    69.0  мужской
9    58.0  женский

In [ ]:
female = df[df['Sex'] == 'женский']
#создали новую таблицу, в которой находятся только женщины

In [20]:
female.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0

In [23]:
male = df[df['Sex'] == 'мужской']
male.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [ ]:
female['Growth'].mean(), male['Growth'].mean()
#Нашли среднее значение роста у мужчин и женщин

(np.float64(165.725), np.float64(179.63636363636363))

In [25]:
female['Age'].mean(), male['Age'].mean()

(np.float64(21.033333333333335), np.float64(20.060606060606062))

In [26]:
female['Age'].median(), male['Age'].median()

(np.float64(20.0), np.float64(20.0))

In [28]:
female['Coin'].value_counts(), male['Coin'].value_counts()

(Coin
 Орел     64
 Решка    56
 Name: count, dtype: int64,
 Coin
 Орел     54
 Решка    12
 Name: count, dtype: int64)

In [ ]:
df1 = df[df['Growth'] < 165]
df2 = df[(df['Growth'] >= 165) & (df['Growth'] <= 175)]
df3 = df[df['Growth'] > 175]
#разделили студентов по росту на 3 группы:
#1) студенты с ростом больше 165
#2) студенты с ростом 165 и больше и студеннты с ростом 175 и меньше
#3) студенты с ростом больше 175

In [ ]:
df1['Growth'].mean(), df2['Growth'].mean(), df3['Growth'].mean()

(np.float64(160.66666666666666),
 np.float64(169.16),
 np.float64(182.10526315789474))

In [ ]:
df[df['Age'] + df['Year of birth'] == 2022].shape
#посчитали количество студентов, у которых уже прошло ДР

(102, 48)

In [ ]:
df[df['Growth'] < df['Growth'].mean()].shape
#нашли людей с ростом, который меньше среднего значения роста

(110, 48)

In [ ]:
df[df['Age'] == df['Age'].min()]
#нашли людей с наименьшим возрастом

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
115,17,175,41,0,2004,152,96,80,0,83,...,1000,КитКат,1.0,СоцГум,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),3,2.0,5.0
126,17,168,39,0,2004,110,91,72,0,83,...,1000,Марс,800000.0,Экономический,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),5,7.0,15.0

In [ ]:
df[df['Age'] == df['Age'].max()]
#нашли человека с наибольшем возрастом

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
81,55,160,37,7,1960,2000,0,0,0,0,...,300,Милки Вей,800000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),10,10.0,10.0

In [41]:
df[df['Weight'] == df['Weight'].max()]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0